### ISSUE TITLE
A bug in CNV.focal

### ISSUE THREAD

**Issue by kyasuno** [hovestadtlab/conumee2#3]
Hi, 

CNV.focal reports an error, 

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'split': object 'x' not found

which might be associated with the following two lines: 

348: cgenes.ratio <- sapply(split(x@fit$ratio[d2[, "probe"],i], d2[, "gene"]), median, na.rm = TRUE)[values(cgenes)$SYMBOL]
349: cgenes.ratio <- cgenes.ratio - x@bin$shift[i]

I think "x" must be replaced by "object". 

In addition, gene annotations created in CNV.create_anno by using UCSC_RefGene_Name_450k are not matched with 
probe order. 

probes450k <- minfi::getLocations(IlluminaHumanMethylation450kanno.ilmn12.hg19::IlluminaHumanMethylation450kanno.ilmn12.hg19)
probes450k$genes <- UCSC_RefGene_Name_450k

Thanks,

Katsuhito

**Comment by bjarnedae** [comment]
Hi Katsuhito, 

thank you so much for your comment! I revised the code by replacing "x" with "object". 

Concerning the probe order, the probes from the 450k and EPIC arrays are sorted subsequently. It is ensured that the gene annotation for each probe is correct. 

Your comment is very helpful for improving the package. Please do not hesitate to contact me in case you encounter further issues. 

Thanks, 
Bjarne

**Comment by kyasuno** [comment]
Hi Bjarne. 

It appears that the correction has not been reflected. 
I'm looking forward to using CNV.focal. 

Thanks,
Katsuhito
