### ISSUE TITLE
To add more detail regions

### ISSUE THREAD

**Issue by kwanghoon821** [hovestadtlab/conumee2#4]
Hello.

I have a question about the detail region.
If I want to add more genes to exclude or add, should I make the BED file like below?
And read as a dataframe or something?

![image](https://github.com/hovestadtlab/conumee2/assets/57473524/90d5a9be-60bd-412e-960a-e91e173147c8)

And what is the meaning of columns? 'score', 'probes_gene', 'probes_promoter'

Thank you!

**Comment by bjarnedae** [comment]
Hi, 

thank you for your patience! You could use a customized BED file, but I recommend to modify the `detail_regions` GRanges object. You obtain it with: 

`data("detail_regions")` (hg19) or `data("detail_regions.hg38")` (hg38)
