### ISSUE TITLE
how to set hg38 for annotation genome?

### ISSUE THREAD

**Issue by seetarajpara** [hovestadtlab/conumee2#5]
Just wanted to know if there was a way to specify the hg38 reference genome for the `CNV.create_anno` step, I couldn't find any arguments that allow this but I could have missed something. Thank you!

**Comment by bjarnedae** [comment]
Hi, 
thank you for your question. Currently there is no way to specify the hg38 reference genome, but a liftover from the EPICv2 probe annotations has been performed and is used as a reference in the CNV.create_anno function for EPICv2 arrays.

**Comment by bjarnedae** [comment]
Hi, 

we just released an update that provides support for hg38 annotation. Please use:

```
data("detail_regions.hg38")
anno <- CNV.create_anno(array_type = "EPICv2", genome = hg38, detail_regions = detail_regions)
```

Best regards, 
Bjarne
